[package]
name = "proxyapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.64"
hyper = {version="0.14.23", features=["full"]}
openssl = "0.10.45"
tokio-rustls = "0.23.4"
tokio-tungstenite = "0.18.0"
